/run/initialize
/run/printProgress 10
/gun/particle gamma
/gun/energy 5 GeV
/gun/position 0. 0. 0. m

#eta MiddleDeltaEta*16-MiddleDeltaEta/2. phi MiddleDeltaPhi/2.
/gun/direction 0.929279 0.0114045 0.369203

#eta 0.4 phi 0
#/gun/direction 0.925007 0. 0.379949

#eta 0.8 phi 0 (half calo)
#/gun/direction 0.7477 0. 0.664037

#eta 1.475 phi 0 (edge of calo)
#/gun/direction 0.4348 0. 900527

#eta 0.4 phi M_PI/16
#/gun/direction 0.907234 0.18046 0.379949

/run/beamOn 100
